spring:
  application:
    name: provider-application-another

  cloud:
    tutu:
      discovery:
        server-addr: localhost:6688
        service: ${spring.application.name}

# 随机端口
server:
  port: ${random.int[20000,30000]}
